"""initial schema

Revision ID: eac3c7e76580
Revises:
Create Date: 2026-10-01 23:25:52.884213
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eac3c7e76580"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("row_pk", sa.String(length=64), nullable=False),
        sa.Column("op", sa.String(length=16), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("origin_instance", sa.String(length=32), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("config_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_config_events_ts"), ["ts"], unique=False)

    op.create_table(
        "counters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=True),
        sa.Column("window", sa.String(length=8), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.BigInteger(), nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), nullable=False),
        sa.Column("tokens_total", sa.BigInteger(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_id", "window", "window_start"),
    )
    with op.batch_alter_table("counters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_counters_key_id"), ["key_id"], unique=False)
        batch_op.create_index("ix_counters_prune", ["window", "window_start"], unique=False)

    op.create_table(
        "model_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("price_in", sa.Float(), nullable=False),
        sa.Column("price_out", sa.Float(), nullable=False),
        sa.Column("price_cache_read", sa.Float(), nullable=False),
        sa.Column("price_cache_write", sa.Float(), nullable=False),
        sa.Column("context_window", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_prices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_prices_effective_until"), ["effective_until"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_model_prices_model"), ["model"], unique=False)
        batch_op.create_index(
            "ix_model_prices_model_current", ["model", "effective_until"], unique=False
        )

    op.create_table(
        "peers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("endpoint_url", sa.String(length=512), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("secret_handle", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("timeout_s", sa.Double(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "virtual_keys",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("secret_handle", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("project", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_from", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("allowed_providers", sa.JSON(), nullable=True),
        sa.Column("allowed_models_aliases", sa.JSON(), nullable=True),
        sa.Column("blocked_reason", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("virtual_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_virtual_keys_key_hash"), ["key_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_virtual_keys_prefix"), ["prefix"], unique=False)
        batch_op.create_index(batch_op.f("ix_virtual_keys_status"), ["status"], unique=False)

    op.create_table(
        "aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_name", sa.String(length=128), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("upstream_model", sa.String(length=256), nullable=False),
        sa.Column("fallbacks", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias_name"),
    )
    op.create_table(
        "limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=True),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("window", sa.String(length=8), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("auto_block", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["key_id"], ["virtual_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_id", "metric", "window"),
    )
    with op.batch_alter_table("limits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_limits_key_id"), ["key_id"], unique=False)

    op.create_table(
        "request_logs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("instance_id", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=256), nullable=True),
        sa.Column("alias_used", sa.String(length=128), nullable=True),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("latency_total_ms", sa.Float(), nullable=True),
        sa.Column("upstream_ms", sa.Float(), nullable=True),
        sa.Column("tokens_in", sa.BigInteger(), nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), nullable=False),
        sa.Column("cache_read", sa.BigInteger(), nullable=False),
        sa.Column("cache_write", sa.BigInteger(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("price_band_id", sa.Integer(), nullable=True),
        sa.Column("is_stream", sa.Boolean(), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request_bytes", sa.BigInteger(), nullable=True),
        sa.Column("response_bytes", sa.BigInteger(), nullable=True),
        sa.Column("request_preview", sa.Text(), nullable=True),
        sa.Column("response_preview", sa.Text(), nullable=True),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("fallback_hops", sa.JSON(), nullable=True),
        sa.Column("synced", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["price_band_id"],
            ["model_prices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_id", "id"),
    )
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_request_logs_key_id"), ["key_id"], unique=False)
        batch_op.create_index(
            "ix_request_logs_query", ["ts", "key_id", "provider", "model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_logs_synced"), ["synced"], unique=False)
        batch_op.create_index(batch_op.f("ix_request_logs_ts"), ["ts"], unique=False)

    op.create_table(
        "sync_state",
        sa.Column("peer_id", sa.Integer(), nullable=False),
        sa.Column("last_sent_cursor", sa.String(length=26), nullable=False),
        sa.Column("last_received_cursor", sa.String(length=26), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["peer_id"], ["peers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("peer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_state")
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_logs_ts"))
        batch_op.drop_index(batch_op.f("ix_request_logs_synced"))
        batch_op.drop_index("ix_request_logs_query")
        batch_op.drop_index(batch_op.f("ix_request_logs_key_id"))

    op.drop_table("request_logs")
    with op.batch_alter_table("limits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_limits_key_id"))

    op.drop_table("limits")
    op.drop_table("aliases")
    with op.batch_alter_table("virtual_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_virtual_keys_status"))
        batch_op.drop_index(batch_op.f("ix_virtual_keys_prefix"))
        batch_op.drop_index(batch_op.f("ix_virtual_keys_key_hash"))

    op.drop_table("virtual_keys")
    op.drop_table("settings")
    op.drop_table("providers")
    op.drop_table("peers")
    with op.batch_alter_table("model_prices", schema=None) as batch_op:
        batch_op.drop_index("ix_model_prices_model_current")
        batch_op.drop_index(batch_op.f("ix_model_prices_model"))
        batch_op.drop_index(batch_op.f("ix_model_prices_effective_until"))

    op.drop_table("model_prices")
    with op.batch_alter_table("counters", schema=None) as batch_op:
        batch_op.drop_index("ix_counters_prune")
        batch_op.drop_index(batch_op.f("ix_counters_key_id"))

    op.drop_table("counters")
    with op.batch_alter_table("config_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_events_ts"))

    op.drop_table("config_events")
    # ### end Alembic commands ###
